### ISSUE TITLE
https://github.com/sushchyk/eurodiffusion/blob/master/src/CoinsDiffusioner.php#L53

### ISSUE THREAD

**Issue by IanaKhitsko** [sushchyk/eurodiffusion#2]
if (count($this->completedCountries) === count($this->cities)) {
            return $this->completedCountries;
==

Again, why shall completedCountries be equal to cities count? Maybe the variable was named incorrectly or  corresponds to the different entity

**Comment by sushchyk** [comment]
You are right, it named incorrectly.
`cities` is map (associative array), where key is country name, and value - array of Country objects.
I renamed it to `citiesByCountry`
